# This file was generated by GoReleaser. DO NOT EDIT.
class Kboard < Formula
  desc "Terminal game to practice keyboard typing"
  homepage "https://github.com/CamiloGarciaLaRotta/kboard"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.2/kboard_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "d122fce134cc8b4ed2cdcb01698e2ef7b0c9a982e800bec31f1cb2d2e6bcdd7f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.2/kboard_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ee3dc34067b035d49c4adb5f02d6abbac7b806dbd1c1087ecb89a67bc77c951d"
    end
  end

  def install
    bin.install "kboard"
  end

  test do
    system "#{bin}/kboard -h"
  end
end
