# This file was generated by GoReleaser. DO NOT EDIT.
class Kboard < Formula
  desc "Terminal game to practice keyboard typing"
  homepage "https://github.com/CamiloGarciaLaRotta/kboard"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.0/kboard_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "014ea45829504d7af7a4a10f0583a59904bfac09b15b5d7e571bed47c93e34e1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.0/kboard_0.1.0_Linux_x86_64.tar.gz"
      sha256 "43453521888872ea87aee8794653a18adab465e360a6ebbb92f6634b5a63d2e5"
    end
  end

  def install
    bin.install "kboard"
  end

  test do
    system "#{bin}/kboard"
  end
end
