# This file was generated by GoReleaser. DO NOT EDIT.
class Kboard < Formula
  desc "Terminal game to practice keyboard typing"
  homepage "https://github.com/CamiloGarciaLaRotta/kboard"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.1/kboard_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "61635a3d653bee799f7831b6a93e382454eeb65df2e7bf33dec50f4e4d39007b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/CamiloGarciaLaRotta/kboard/releases/download/v0.1.1/kboard_0.1.1_Linux_x86_64.tar.gz"
      sha256 "3851ef93bc0b19eb6d0e62d83b3f0dafcaa261486ac3d9dfdc9ba4e75cc89c90"
    end
  end

  def install
    bin.install "kboard"
  end

  test do
    system "#{bin}/kboard -h"
  end
end
